import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import HeroSection from "@/Components/HeroSection";
import FeatureSection from "@/Components/FeatureSection";
import WhyChooseUs from "@/Components/WhyChooseUs";
import DestimonialCards from "@/Components/DestimonialCards";
import UpComingWeb from "@/Components/ui/UpComingWeb";
import Instractor from "@/Components/Instractor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {children}
        <div className=" flex items-center justify-center relative w-full">
          <Navbar />
        </div>
        <HeroSection />
        <FeatureSection />
        <WhyChooseUs />
        <DestimonialCards />
        <UpComingWeb />
        <Instractor />

      </body>
    </html>
  );
}
